local facts = {
	"Cat's cannot taste sweet things",
	"Surgeons who listen to music during operations perform better than those who don't.",
	"The great wall of China is 1,400 miles long",
	"Women blink nearly twice as much as men.",
	"Donkeys kill more people annually than plane crashes.",
	"Each year 96 billion pounds of food is wasted in the U.S.",
	"Lightning strikes about 6,000 times per minute on this planet",
	"A bird 'chews' with its stomach.",
	"On average, half of all false teeth have some form of radioactivity.",
	"It was discovered on a space mission that a frog can throw up.",
	"The heart of an astronaut actually gets smaller when in outer space.",
	"Your heart pumps about 2,000 gallons of blood each day",
	"Someone on Earth reports seeing a UFO every three minutes.",
	"The speed of a typical raindrop is 17 miles per hour.",
	"The first product to have a bar code was Wrigleys gum",
	"Samar = best person",
	"Ves is world's best prison life scripter",
	"Americans, on average, spend 18% of his or her income on transportation as compared to only 13% spent on food.",
	"A kangaroo can only jump if its tail is touching the ground.",
	"Surgeon scrubs are green to counteract eye stress from all the red blood (opposite colors).",
	"'Western' numerals (i.e. 0-9) are actually called Arabic numerals",
	"The only word in the English language with three consecutive sets of double letters is 'bookkeeper'",
	"On average, there are 178 sesame seeds on each McDonalds BigMac bun",
	"There are 336 dimples in a regulation golf ball.",
	"One thousand words make up 90% of common speech.",
}

return facts
